spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/big_data?autoReconnect=true&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  task:
    scheduling:
      pool:
        size: 30
      thread-name-prefix: task-process
cms:
  id: ce97bca829f211eeb38000fffbe0bbcc