spring:
  profiles:
    active: dev
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
mybatis-plus:
  configuration:
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true